//["ROLE_USER","ROLE_EPAY","ROLE_ADMIN","ROLE_MODERATOR"]
export enum Role {
  USER = 'ROLE_USER',
  ACV = 'ROLE_ACV',
  EPAY = 'ROLE_EPAY',
  NAPAS = 'ROLE_NAPAS',
  ADMIN = 'ROLE_ADMIN',
  MODERATOR = 'ROLE_MODERATOR',
  FREE = 'ROLE_FREE',
}
